name: Trigger auto deployment for ca-quotes-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'src/backend/QuotesService/**'
    - '.github/workflows/ca-quotes-backend-AutoDeployTrigger-32b1e5bf-0c19-4b4d-9986-b2bb59676323.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAQUOTESBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAQUOTESBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAQUOTESBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src/backend/QuotesService 
          registryUrl: icdregistry.azurecr.io
          registryUsername: ${{ secrets.CAQUOTESBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAQUOTESBACKEND_REGISTRY_PASSWORD }}
          containerAppName: ca-quotes-backend
          resourceGroup: icd
          imageToBuild: icdregistry.azurecr.io/ca-quotes-backend:${{ github.sha }}
          dockerfilePath: Dockerfile


