name: Trigger auto deployment for ca-quotes

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/ca-quotes-AutoDeployTrigger-33ef04b4-d5d5-49c6-b1a6-42b23786b46a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAQUOTES_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAQUOTES_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAQUOTES_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: icdregistry.azurecr.io
          registryUsername: ${{ secrets.CAQUOTES_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAQUOTES_REGISTRY_PASSWORD }}
          containerAppName: ca-quotes
          resourceGroup: icd
          imageToBuild: icdregistry.azurecr.io/ca-quotes:${{ github.sha }}
          dockerfilePath: Dockerfile


